### PR TITLE
manage files for users unless they opt out

### PR DESCRIPTION
**Pull request by StevenClontz**
rebased upon main, replaces #592

### CODE REVIEW

**Comment by rbeezer** [comment]
PreTeXt already does some file management (aka directory management) and I would prefer the two would not be confused.  Could you just as well use something like:
```
# Managed by the PreTeXt-CLI
```
or similar to make it clear this is a front-end function?

**Comment by StevenClontz** [comment]
I'm failing at Git management today. Closing and making a clean commit based upon main

**Comment by StevenClontz** [comment]
> PreTeXt already does some file management (aka directory management) and I would prefer the two would not be confused. Could you just as well use something like:
> 
> ```
> # Managed by the PreTeXt-CLI
> ```
> 
> or similar to make it clear this is a front-end function?

In #594 I've amended this to look for `<!-- Managed automatically by PreTeXt authoring tools -->`

**Comment by rbeezer** [comment]
`<!-- Managed automatically by PreTeXt authoring tools -->`

I like it!  Thanks.

**Pull request closed without merging**
