### PR TITLE
Attempt to address #414

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by oscarlevin** [comment]
It appears that temp directories are being left behind by `pretext generate` as well.

Is there an advantage to keeping the temp directories when `pretext -v debug` is called?

**Comment by StevenClontz** [comment]
It's unclear to me that more verbose output should be hardwired to not cleaning up temp directories. I'd rather it be a separate switch.

**Comment by oscarlevin** [comment]
What about doing something different if there is an error?  Like copying the temporary directory to a "failed" subfolder of output for inspection.  

Or we can do `core.release_temporary_directories()` at the end of the `try` , which would leave the directory if there is an exception.

I'm adding the `core.release_temporary_directories()` to generate now.

**Comment by rbeezer** [comment]
There is a module-level variable with a list of all the temporary directories created.  So the CLI can handle clean-up in any way you think is appropriate.  If you don't tlike the variable, you could add a method to core to just return the list - that might be best anyway.

**Comment by oscarlevin** [comment]
It looks like we can do all the cleanup at once in a single spot (there is an `exit_command` function already to deal with logging).

However, this has two issues that would need @rbeezer's attention.  First, for some reason, latex-image's temp directories don't get deleted on windows, and this throws an error, unless we set `ignore_errrors=True` on 3811 of pretext/pretext.  Second, we get a bunch of unhelpful info messages spit out after our "success" message.  Thoughts about removing this log message (or putting it in debug, which doesn't get read by anything except our log-file writer)?

**Comment by rbeezer** [comment]
>  First, for some reason, latex-image's temp directories don't get deleted on windows, and this throws an error, unless we set ignore_errrors=True on 3811 of pretext/pretext. 

I took a hard look to see what could be different there.  That routine can end by throwing a `ValueError`, but you would have caught that and seen it?

Maybe the run of LaTeX is still holding some file?  `subprocess.run()` is suppose to be better than the alternatives, so maybe not that.

Might you try deleting individual files and see if there is one in particular?

**Comment by rbeezer** [comment]
> Second, we get a bunch of unhelpful info messages spit out after our "success" message. Thoughts about removing this log message (or putting it in debug, which doesn't get read by anything except our log-file writer)?

I find them helpful.  ;-)

You could move your success message?

If it goes into the debug messages it won't ever say anything, since they are not being deleted?

I think a getter in core for the list of temporary directories is the best route for the CLI to manage this.  Then the release function can move into  `pretext/pretext`.

**Comment by oscarlevin** [comment]
Okay, for the release message, I've moved some things around so it is not a big deal that they get reported.  

The `release_template_directories()` is in pretext/pretext, so I don't know what you mean about the getter comment.

Still not sure about the windows error.  It is not that subprocess.run() needs `shell=True`, which fixed issues I've seen like this previously.  I'll keep looking.  Strangely, if you use `ignore_errors=True`, then all the files in the temporary directory get deleted, but the directory itself does not.

**Comment by rbeezer** [comment]
> The release_template_directories() is in pretext/pretext

I see `release_temporary_directories()` defined in pretext/pretext.py.

> so I don't know what you mean about the getter comment.

Add a function to  `pretext.py` that returns the list in `__temps` (`get_temporary_directories()`?).  Then CLI code can call that function and delete the directories when and how it wants to.

**Comment by oscarlevin** [comment]
Gotcha.  If we need to be more clever than we are now, that is what we will do.

I found the issue with not being able to delete temporary directories: a few times, pretext/pretext changes into the temporary directory (to run latex stuff) and doesn't change back out at the end.  Pull request on core coming right up.

**Comment by rbeezer** [comment]
> I found the issue with not being able to delete temporary directories:

Aah ha!  Beautiful.  Thanks for chasing that down.  I'll follow-up  with https://github.com/PreTeXtBook/pretext/pull/1925 in the morning.

**Pull request merged**
