### PR TITLE
`warning: 'NoneType' object has no attribute 'split'`

### PR DESCRIPTION
**Pull request by StevenClontz**
Caught at https://github.com/TeamBasedInquiryLearning/precalculus/issues/230

### CODE REVIEW

**Comment by StevenClontz** [comment]
Okay, there are two issues here.

1. We have the ability to save the `sage` executable as `None`, which is supposed to rely on some sort of server solution. However, we're failing to do this, and we're running `split()` on the `None` object.
2. Our codespace no longer ships with Sage.

**Comment by StevenClontz** [comment]
This is an upstream bug in core PreTeXt - `core.get_executable_cmd(exec_name)` raises this error if `__executables[exec_name]` returns `None`.

**Comment by StevenClontz** [comment]
Well, define "bug". We're the one that is setting that value to be `None` at https://github.com/PreTeXtBook/pretext-cli/blob/4ce468b30a74fe378bfd911c6d64b44f6819c82f/pretext/project/__init__.py#L1272 My guess is that this is not Rob's intended behavior.

**Comment by StevenClontz** [comment]
The NoneType error has been fixed as of 2a51a75.

But the bigger issue is that we're no longer shipping SageMath in our Codespace.

**Review by oscarlevin — APPROVED** [review]
Looks good to me.

**Pull request merged**
