### PR TITLE
Add: Use flake8 for linting.

### PR DESCRIPTION
**Pull request by bjones1**
Per the discussion in https://github.com/PreTeXtBook/pretext-cli/pull/370#issuecomment-1353404886.

Thoughts:
- I suggest that I open a separate PR with fixes for all the issues flake8 complains about, so we can discuss which merit fixing and which should be ignored before merging this PR.
- We should ignore lint issues in `core/pretext.py`, since the source comes from another repo. Are there any other files that come from elsewhere and should therefore be ignored?

Output from flake8
=============
```
.\pretext\build.py:48:23: F541 f-string is missing placeholders
.\pretext\build.py:75:23: F541 f-string is missing placeholders
.\pretext\build.py:104:23: F541 f-string is missing placeholders
.\pretext\build.py:138:23: F541 f-string is missing placeholders
.\pretext\build.py:168:23: F541 f-string is missing placeholders
.\pretext\build.py:196:23: F541 f-string is missing placeholders
.\pretext\build.py:229:23: F541 f-string is missing placeholders
.\pretext\cli.py:1:1: F401 'concurrent.futures.process._threads_wakeups' imported but unused
.\pretext\cli.py:2:1: F401 'pickle.FALSE' imported but unused
.\pretext\cli.py:15:1: F811 redefinition of unused 'shutil' from line 8
.\pretext\cli.py:185:21: F541 f-string is missing placeholders
.\pretext\cli.py:244:13: F541 f-string is missing placeholders
.\pretext\cli.py:309:14: F541 f-string is missing placeholders
.\pretext\cli.py:311:9: F541 f-string is missing placeholders
.\pretext\cli.py:465:20: E711 comparison to None should be 'if cond is None:'
.\pretext\core\__init__.py:2:5: F403 'from .pretext import *' used; unable to detect undefined names
.\pretext\core\__init__.py:11:1: F405 'set_ptx_path' may be undefined, or defined from star imports: .pretext
.\pretext\generate.py:6:1: F401 'typing.Optional' imported but unused
.\pretext\generate.py:65:31: F541 f-string is missing placeholders
.\pretext\generate.py:126:27: F541 f-string is missing placeholders
.\pretext\generate.py:185:27: F541 f-string is missing placeholders
.\pretext\generate.py:224:27: F541 f-string is missing placeholders
.\pretext\generate.py:255:27: F541 f-string is missing placeholders
.\pretext\generate.py:291:27: F541 f-string is missing placeholders
.\pretext\generate.py:325:27: F541 f-string is missing placeholders
.\pretext\project.py:225:17: E722 do not use bare 'except'
.\pretext\project.py:362:23: F541 f-string is missing placeholders
.\pretext\project.py:470:13: E722 do not use bare 'except'
.\pretext\project.py:529:18: F541 f-string is missing placeholders
.\pretext\project.py:551:9: E722 do not use bare 'except'
.\pretext\project.py:557:33: F541 f-string is missing placeholders
.\pretext\utils.py:3:1: F401 'glob' imported but unused
.\pretext\utils.py:13:1: F811 redefinition of unused 'subprocess' from line 1
.\pretext\utils.py:17:23: E401 multiple imports on one line
.\pretext\utils.py:50:16: E711 comparison to None should be 'if cond is None:'
.\pretext\utils.py:67:14: F821 undefined name 'templates'
.\pretext\utils.py:75:16: E711 comparison to None should be 'if cond is None:'
.\pretext\utils.py:89:16: E711 comparison to None should be 'if cond is None:'
.\pretext\utils.py:97:16: E711 comparison to None should be 'if cond is None:'
.\pretext\utils.py:151:5: E266 too many leading '#' for block comment
.\pretext\utils.py:173:5: E722 do not use bare 'except'
.\pretext\utils.py:186:9: E306 expected 1 blank line before a nested definition, found 0
.\pretext\utils.py:253:21: F541 f-string is missing placeholders
.\pretext\utils.py:257:30: F541 f-string is missing placeholders
.\pretext\utils.py:275:5: F841 local variable 'binding' is assigned to but never used
.\pretext\utils.py:478:49: E741 ambiguous variable name 'l'
.\pretext\utils.py:479:44: E741 ambiguous variable name 'l'
.\pretextbook\setup.py:6:1: F821 undefined name 'setup'
.\scripts\fetch_core.py:9:1: F811 redefinition of unused 'os' from line 6
.\scripts\fetch_core.py:9:1: F401 'os' imported but unused
.\scripts\release_nightly.py:8:1: F401 'tomli' imported but unused
.\scripts\release_nightly.py:84:5: E722 do not use bare 'except'
.\scripts\symlink_core.py:2:1: F401 'shutil' imported but unused
.\setup.py:6:1: F821 undefined name 'setup'
.\tests\test_cli.py:6:1: F401 'signal' imported but unused
.\tests\test_cli.py:7:1: F401 'platform' imported but unused
.\tests\test_cli.py:10:1: F401 'tempfile.TemporaryDirectory' imported but unused
.\tests\test_xml_overlay.py:2:1: F401 'typing as t' imported but unused
```

### CODE REVIEW

**Comment by bjones1** [comment]
@StevenClontz and @oscarlevin, I'd appreciate your feedback on this when you have time. Thanks!

**Comment by bjones1** [comment]
Note that this PR's test will fail until all the lint it identifies is resolved.

**Comment by bjones1** [comment]
I rebased this to resolve conflicts. Merge #382 before this.

**Comment by StevenClontz** [comment]
I'm unsure if we need to update `.git-blame-ignore-revs` on this one as the code changes aren't pervasive as they were for when we started enforcing black formatting.

**Comment by bjones1** [comment]
> I'm unsure if we need to update `.git-blame-ignore-revs` on this one as the code changes aren't pervasive as they were for when we started enforcing black formatting.

I would suggest not adding this -- the changes aren't large.

**Comment by bjones1** [comment]
Where do I add a link to install the VSCode flake8 extension? Here's [a link](https://code.visualstudio.com/docs/python/linting).

**Comment by bjones1** [comment]
@oscarlevin, this is ready!

**Comment by oscarlevin** [comment]
Looks great.  Thank you!

**Comment by bjones1** [comment]
My pleasure!

**Pull request merged**
