### PR TITLE
skip targets with invalid publication files

### PR DESCRIPTION
**Pull request by StevenClontz**
This should ensure that v1 project files with targets that have non-existent publication files still validate (but those targets with bad publication files won't be available).

### CODE REVIEW

**Comment by StevenClontz** [comment]
There's gotta be a way for a bot to create a new PR fixing formatting issues if that's the only problem with a PR...

**Comment by bnmnetp** [comment]
The build today failed for four books....

dmoi - failed because, I think, because of the line break in:
```
<format>
    html</format>
```
For ula I get the error:

```
critical: Failed to parse project.ptx. Check the entire file, including all targets, and fix the following errors:
1 validation error for Target
site
  Extra inputs are not permitted [type=extra_forbidden, input_value='.', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/extra_forbidden
{'type': 'extra_forbidden', 'loc': ('site',), 'msg': 'Extra inputs are not permitted', 'input': '.', 'url': 'https://errors.pydantic.dev/2.4/v/extra_forbidden'}
error: Either one of the targets or the root project element has an extra attribute it shouldn't: site="."
```
But I cannot find the string "site" in the project file. the only thing I can find that might be the trouble is
```
<deploy-dir>.</deploy-dir>
```

Tom's odeproject fails with:
```

critical: Failed to parse project.ptx. Check the entire file, including all targets, and fix the following errors:
error: Either one of the targets or the root project element has an extra attribute it shouldn't: format="html"
error: Either one of the targets or the root project element has an extra attribute it shouldn't: source="source/main.ptx"
error: Either one of the targets or the root project element has an extra attribute it shouldn't: publication="publication/publication.ptx"
error: Either one of the targets or the root project element has an extra attribute it shouldn't: output-dir="output/html"
----------------------------------------------------
```

And finally APEX builds, but fails later because Sean has moved to the new 2.0 format.  Which I do not support yet.

**Comment by oscarlevin** [comment]
Thanks for the report.  

I've set up pydantic to now strip whitespace on strings.  So that should fix those issues.

The site vs deploy-dir was an old bug that was doubly broken, but got half-fixed with the most recent release.  I think I have it fixed now.

I don't know what's going on with tom's ode project.  I found a repository for it, but it has a v2 project.ptx.  If you can point me to the repository you pull from, I can investigate further.

**Comment by bnmnetp** [comment]
https://github.com/twjudson/odeproject-public.git

**Comment by oscarlevin** [comment]
That does have a v2 project file.  So that must be part of the issue.

**Comment by bnmnetp** [comment]
Ahhh,

```
<project ptx-version="2">
  <targets>
    <target name="html">
      <format>html</format>
      <source>source/main.ptx</source>
      <publication>publication/publication.ptx</publication>
      <output-dir>output/html</output-dir>
    </target>
    <target name="runestone">
      <format>html</format>
      <source>source/main.ptx</source>
      <publication>publication/publication-academy.ptx</publication>
      <output-dir>published/odeproject</output-dir>
    </target>
...
```
is has the version set to 2 but looks like the old format to me.

**Comment by oscarlevin** [comment]
I'm guessing that was the result of a strange merge.  If the project file has the version set to 2, then it cannot have the version one format.  If you remove the version, it should work.

**Comment by bnmnetp** [comment]
Tried that just now :-) No dice.

```
critical: Failed to parse project.ptx. Check the entire file, including all targets, and fix the following errors:
error: One of the targets has a missing required attribute: executables; look for the target with {'targets': [LegacyTarget(name='html', latex_engine=None, format=<LegacyFormat.HTML: 'html'>, source='source/main.ptx', publication='publication/publication.ptx', output_dir=PosixPath('output/html'), output_filename=None, site=None, xsl=None, asy_method='server', stringparams=[]), LegacyTarget(name='runestone', latex_engine=None, format=<LegacyFormat.HTML: 'html'>, source='source/main.ptx', publication='publication/publication-academy.ptx', output_dir=PosixPath('published/odeproject'), output_filename=None, site=None, xsl=None, asy_method='server', stringparams=[]), LegacyTarget(name='latex', latex_engine=None, format=<LegacyFormat.LATEX: 'latex'>, source='source/main.ptx', publication='publication/publication.ptx', output_dir=PosixPath('output/latex'), output_filename=None, site=None, xsl=None, asy_method='server', stringparams=[]), LegacyTarget(name='pdf', latex_engine=<LatexEngine.XELATEX: 'xelatex'>, format=<LegacyFormat.PDF: 'pdf'>, source='source/main.ptx', publication='publication/publication.ptx', output_dir=PosixPath('output/pdf'), output_filename=None, site=None, xsl=None, asy_method='server', stringparams=[]), LegacyTarget(name='subset', latex_engine=None, format=<LegacyFormat.HTML: 'html'>, source='source/main.ptx', publication='publication/publication.ptx', output_dir=PosixPath('output/subset'), output_filename=None, site=None, xsl=None, asy_method='server', stringparams=[LegacyStringParam(key='debug.skip-knowls', value='yes')])]}.
```

**Comment by bnmnetp** [comment]
Bad merge seems like a good theory.

**Comment by oscarlevin** [comment]
And then it is missing the executables.

**Comment by bnmnetp** [comment]
The `project.ptx` file on github is only 10 lines long.

**Comment by oscarlevin** [comment]
If you go back 2 commits, it has the old publication file.  Using that should work.

**Comment by bnmnetp** [comment]
Yep, just did that, thanks!

**Pull request merged**
