### PR TITLE
Fix: Update to the latest CodeChat Server, to fix bugs running in Codespaces.

### PR DESCRIPTION
**Pull request by bjones1**

### CODE REVIEW

**Comment by bjones1** [comment]
See discussion in #608.

**Comment by StevenClontz** [comment]
Where are we requiring CodeChat in our `pyproject.toml`? If we need to indicate a minimal version, shouldn't it be there?

**Comment by StevenClontz** [comment]
Ah, found it here. https://github.com/PreTeXtBook/pretext-cli/blob/892a298e228485ebd55eda83c16251a1236cde41/pyproject.toml#L50

But, is that right? Is it a dev dependency or are we using it for something in the production library?

In any case, I believe Poetry.lock is only used by users who clone the repo, not for production.

**Comment by bjones1** [comment]
This is necessary to run the CodeChat System, so it's not used directly by the CLI but provides the nice interface to auto-build/sync/view PreTeXt output in VSCode / Codespaces.

**Comment by StevenClontz** [comment]
Right - what I'm saying is that this Poetry.lock isn't impacting what is installed for those who `pip install pretext` (see below). So I don't think this is the place to fix this bug - we need to update CodeChat in Oscar's docker image.

```
👋 Welcome to Codespaces! You are on our default image. 
   - It includes runtimes and tools for Python, Node.js, Docker, and more. See the full list here: https://aka.ms/ghcs-default-image
   - Want to use a custom image instead? Learn more here: https://aka.ms/configure-codespace

🔍 To explore VS Code to its fullest, search using the Command Palette (Cmd/Ctrl + Shift + P or F1).

📝 Edit away, run your app as usual, and we'll automatically make it available for you to access.

@StevenClontz ➜ /workspaces/reimagined-computing-machine (main) $ pip install pretext
Collecting pretext
  Obtaining dependency information for pretext from https://files.pythonhosted.org/packages/70/01/c74dbfbe3dfa86bd2ce993c54619c4499744fd695ab220523fd568c1c0b3/pretext-2.0.4-py3-none-any.whl.metadata
  Downloading pretext-2.0.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: GitPython<4,>=3 in /home/codespace/.local/lib/python3.10/site-packages (from pretext) (3.1.37)
Collecting PyPDF2<2.6,>=2.5 (from pretext)
  Downloading PyPDF2-2.5.0-py3-none-any.whl (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.4/200.4 kB 4.0 MB/s eta 0:00:00
Collecting click<9,>=8 (from pretext)
  Obtaining dependency information for click<9,>=8 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting click-log<0.5,>=0.4 (from pretext)
  Downloading click_log-0.4.0-py2.py3-none-any.whl (4.3 kB)
Collecting ghp-import<3,>=2 (from pretext)
  Downloading ghp_import-2.1.0-py3-none-any.whl (11 kB)
Collecting lxml<5.0,>=4.8 (from pretext)
  Obtaining dependency information for lxml<5.0,>=4.8 from https://files.pythonhosted.org/packages/3c/d2/11533f0bc47ff4d828a20cfb702f3453fe714bd5b475fcdc8cec6e6b7dcf/lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl.metadata
  Downloading lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting pdfCropMargins<1.1.0,>=1.0.9 (from pretext)
  Downloading pdfCropMargins-1.0.9.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 24.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting playwright<2,>=1 (from pretext)
  Obtaining dependency information for playwright<2,>=1 from https://files.pythonhosted.org/packages/28/ae/19318074f87b4c3c0b0f45ee5a41bbcf013b7d46ce235d018adb1da97f7b/playwright-1.38.0-py3-none-manylinux1_x86_64.whl.metadata
  Downloading playwright-1.38.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: psutil<6,>=5 in /home/codespace/.local/lib/python3.10/site-packages (from pretext) (5.9.5)
Collecting pyMuPDF<2.0,>=1.23 (from pretext)
  Obtaining dependency information for pyMuPDF<2.0,>=1.23 from https://files.pythonhosted.org/packages/b4/75/748baa46746a4b2cb6dee2f04d8dca18b75c0163104fc809947ad1a9929c/PyMuPDF-1.23.4-cp310-none-manylinux2014_x86_64.whl.metadata
  Downloading PyMuPDF-1.23.4-cp310-none-manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting pydantic-xml>=2 (from pretext)
  Obtaining dependency information for pydantic-xml>=2 from https://files.pythonhosted.org/packages/d5/84/a0a33efec22d6a560b8cf8047d932c520fd2bf19e6ca3097b04157cf306c/pydantic_xml-2.2.4-py3-none-any.whl.metadata
  Downloading pydantic_xml-2.2.4-py3-none-any.whl.metadata (5.0 kB)
Collecting qrcode<8,>=7 (from pretext)
  Downloading qrcode-7.4.2-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from pretext) (2.31.0)
Collecting single-version<2,>=1 (from pretext)
  Obtaining dependency information for single-version<2,>=1 from https://files.pythonhosted.org/packages/61/b5/ffbbc700075f6d07164dea524b81a495689d18a0f6dd44f07c8cdfeb9fb5/single_version-1.6.0-py3-none-any.whl.metadata
  Downloading single_version-1.6.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/codespace/.local/lib/python3.10/site-packages (from ghp-import<3,>=2->pretext) (2.8.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/codespace/.local/lib/python3.10/site-packages (from GitPython<4,>=3->pretext) (4.0.10)
Requirement already satisfied: wheel in /home/codespace/.local/lib/python3.10/site-packages (from pdfCropMargins<1.1.0,>=1.0.9->pretext) (0.41.2)
Requirement already satisfied: pillow>=9.0.0 in /home/codespace/.local/lib/python3.10/site-packages (from pdfCropMargins<1.1.0,>=1.0.9->pretext) (10.0.1)
Collecting greenlet==2.0.2 (from playwright<2,>=1->pretext)
  Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 kB 15.9 MB/s eta 0:00:00
Collecting pyee==9.0.4 (from playwright<2,>=1->pretext)
  Downloading pyee-9.0.4-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: typing-extensions in /home/codespace/.local/lib/python3.10/site-packages (from pyee==9.0.4->playwright<2,>=1->pretext) (4.8.0)
Collecting pydantic>=2.0.0 (from pydantic-xml>=2->pretext)
  Obtaining dependency information for pydantic>=2.0.0 from https://files.pythonhosted.org/packages/73/66/0a72c9fcde42e5650c8d8d5c5c1873b9a3893018020c77ca8eb62708b923/pydantic-2.4.2-py3-none-any.whl.metadata
  Downloading pydantic-2.4.2-py3-none-any.whl.metadata (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.6/158.6 kB 4.8 MB/s eta 0:00:00
Collecting PyMuPDFb==1.23.3 (from pyMuPDF<2.0,>=1.23->pretext)
  Obtaining dependency information for PyMuPDFb==1.23.3 from https://files.pythonhosted.org/packages/34/cf/bb6a3bad0ffdea1fb9fcae53de6c1b9187746c32e17377ff8f36b9d98ee4/PyMuPDFb-1.23.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata
  Downloading PyMuPDFb-1.23.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting pypng (from qrcode<8,>=7->pretext)
  Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests<3,>=2->pretext) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests<3,>=2->pretext) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.10/site-packages (from requests<3,>=2->pretext) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.10/site-packages (from requests<3,>=2->pretext) (2023.7.22)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/codespace/.local/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->GitPython<4,>=3->pretext) (5.0.1)
Collecting annotated-types>=0.4.0 (from pydantic>=2.0.0->pydantic-xml>=2->pretext)
  Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl.metadata
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.10.1 (from pydantic>=2.0.0->pydantic-xml>=2->pretext)
  Obtaining dependency information for pydantic-core==2.10.1 from https://files.pythonhosted.org/packages/86/67/d36e2237d84ac96f400e29586da1e21eabf9aa227fc9c3e4410fbc6408de/pydantic_core-2.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading pydantic_core-2.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.1->ghp-import<3,>=2->pretext) (1.16.0)
Downloading pretext-2.0.4-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 22.4 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 3.4 MB/s eta 0:00:00
Downloading lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 6.9 MB/s eta 0:00:00
Downloading playwright-1.38.0-py3-none-manylinux1_x86_64.whl (35.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.4/35.4 MB 26.6 MB/s eta 0:00:00
Downloading pydantic_xml-2.2.4-py3-none-any.whl (32 kB)
Downloading PyMuPDF-1.23.4-cp310-none-manylinux2014_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 54.8 MB/s eta 0:00:00
Downloading PyMuPDFb-1.23.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (30.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.6/30.6 MB 25.2 MB/s eta 0:00:00
Downloading single_version-1.6.0-py3-none-any.whl (4.2 kB)
Downloading pydantic-2.4.2-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.8/395.8 kB 13.5 MB/s eta 0:00:00
Downloading pydantic_core-2.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 39.9 MB/s eta 0:00:00
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Building wheels for collected packages: pdfCropMargins
  Building wheel for pdfCropMargins (setup.py) ... done
  Created wheel for pdfCropMargins: filename=pdfCropMargins-1.0.9-py2.py3-none-any.whl size=1817497 sha256=c6c69c096eeab4eb357f3a9b997cc70072a6d27f65a9050a6258d8b58bdff001
  Stored in directory: /home/codespace/.cache/pip/wheels/7c/d7/31/4cb7ad5be294f776fe30769b6763c1e42e8a72af10293155f0
Successfully built pdfCropMargins
Installing collected packages: pypng, single-version, qrcode, PyPDF2, PyMuPDFb, pyee, pydantic-core, lxml, greenlet, click, annotated-types, pyMuPDF, pydantic, playwright, pdfCropMargins, ghp-import, click-log, pydantic-xml, pretext
Successfully installed PyMuPDFb-1.23.3 PyPDF2-2.5.0 annotated-types-0.6.0 click-8.1.7 click-log-0.4.0 ghp-import-2.1.0 greenlet-2.0.2 lxml-4.9.3 pdfCropMargins-1.0.9 playwright-1.38.0 pretext-2.0.4 pyMuPDF-1.23.4 pydantic-2.4.2 pydantic-core-2.10.1 pydantic-xml-2.2.4 pyee-9.0.4 pypng-0.20220715.0 qrcode-7.4.2 single-version-1.6.0
```

**Pull request closed without merging**
