### PR TITLE
Update deploy workflow to use personal access token

### LINKED ISSUE #671: update `pretext deploy` Git workflow to use personal access token
Continuing conversation from https://github.com/maymk/ExcelCalculus/pull/6

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #671

### CODE REVIEW

**Comment by oscarlevin** [comment]
Closing this as subsequent work improves on it.

**Comment by oscarlevin** [comment]
Actually I think I was confused about which issue this addresses.  @StevenClontz , is this ready to go?

**Comment by StevenClontz** [comment]
Possibly! Need to fix the tests/linting, and double check it actually works...

**Comment by StevenClontz** [comment]
This is now ready - local PTX-CLI users who are working without an initialized Git project are walked through setting one up, including creating a personal access token which is stored in `.git` to emulate passwordless deploys.

**Comment by oscarlevin** [comment]
Thanks for sorting this one out!

**Pull request merged**
