### PR TITLE
Fix: Many flake8 errors.

### PR DESCRIPTION
**Pull request by bjones1**
This fixes most of the flake8 errors (see #371). The remaining errors:

```
.\pretext\core\__init__.py:2:5: F403 'from .pretext import *' used; unable to detect undefined names
.\pretext\core\__init__.py:11:1: F405 'set_ptx_path' may be undefined, or defined from star imports: .pretext
.\pretext\project.py:540:58: F821 undefined name 'repo_name'
.\pretext\project.py:543:31: F821 undefined name 'repo_name'
.\pretext\project.py:544:40: F821 undefined name 'repo_name'
.\pretext\project.py:546:62: F821 undefined name 'repo_name'
.\pretext\project.py:548:59: F821 undefined name 'url'
.\pretext\utils.py:69:14: F821 undefined name 'templates'
.\pretext\utils.py:279:5: F841 local variable 'binding' is assigned to but never used
```

I think several (undefined names) are bugs in the code, but need help fixing these.

### CODE REVIEW

**Comment by bjones1** [comment]
@oscarlevin and @StevenClontz, would you provide some feedback? I can rebase this, but only want to do so if you'd like to take this approach (fix flake8 / linter errors).

**Comment by StevenClontz** [comment]
I'm all for adding flake linting to our black formatting, particularly if it lines up with Runestone's code style. We just need to make sure the README includes instructions for both (ideally, both commandline and VS Code mechanisms).

**Comment by oscarlevin** [comment]
I agree that this is a good idea, as far as I understand flake linting (which isn't very far).  Maybe we can check in at a dev drop-in soon to sort that out and you can show me how to do this for the documentation.  Also, do we need to worry about the large changes messing with the git blame thing that was brought up for the black formatting?  I don't understand what the resolution to that was (and if it will automatically apply to this).

**Comment by bjones1** [comment]
Will yall be at the Friday drop-in? If so, we can talk then and figure this out. In the meantime, I'll rebase the changes.

**Comment by bjones1** [comment]
I've rebased and fixed a few more lint complaints. Would yall consider merging this, so I don't have to rebase again? This doesn't require use of flake8, just fixes errors reported by it in preparation for #371.

**Review by StevenClontz — CHANGES_REQUESTED** [review]
Add `649006e380988c0d48c4bbc35d8896d5ced63fad` to https://github.com/PreTeXtBook/pretext-cli/blob/main/.git-blame-ignore-revs

**Comment by oscarlevin** [comment]
Awesome.  When the tests pass I'll merge this.

**Comment by bjones1** [comment]
Done!

**Comment by bjones1** [comment]
Thanks!

**Pull request merged**
