### PR TITLE
stage site before deployment

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
FYI @oscarlevin I'm working on this now. This will also allow us to nire conveniently write tests for deployment without actually deploying. Am I correct that tests don't yet exist?

**Comment by oscarlevin** [comment]
Ah, I was just about to clean this up and merge.  Good to know.  I'm in a the middle of a discussion post about this.  Maybe slow down so I can share that?

**Comment by StevenClontz** [comment]
Let's sync up at prose.runestone.academy/dropin if you're able to.

**Comment by StevenClontz** [comment]
In addition to tests passing, a spot-check of https://github.com/TeamBasedInquiryLearning/linear-algebra/commit/170e166a06edfca4e93e7b79be6496ca1dee9b58 seems to be working well also.

**Comment by oscarlevin** [comment]
Nice work.  Thanks for taking care of this.

**Pull request merged**
