### PR TITLE
Typo in `linux_path`

### PR DESCRIPTION
**Pull request by daverosoff**
Need package name too

### CODE REVIEW

**Comment by StevenClontz** [comment]
Yep, thanks. will put out a hotfix with this.

**Comment by StevenClontz** [comment]
Dave can you try https://pypi.org/project/pretextbook/0.5.1rc0/ and let me know if it fixes the issue you found and fixed?

**Comment by oscarlevin** [comment]
Thanks @daverosoff for finding this.  VS Code IntelleSense and Oscar intelligence failed me.

**Comment by daverosoff** [comment]
> 
> 
> Dave can you try https://pypi.org/project/pretextbook/0.5.1rc0/ and let me know if it fixes the issue you found and fixed?

I'm sorry, I don't really know how to do that. It's the virtualenvs. I don't understand how to setup python 3.8.5 when I have 3.8.10 already and pipenv complains.

**Comment by oscarlevin** [comment]
You could `pip install pretextbook==0.5.1rc0` and run your normal pretext commands.

**Comment by daverosoff** [comment]
Thanks Oscar. I did that and the build seems to succeed.

**Comment by StevenClontz** [comment]
Thanks all, https://pypi.org/project/pretextbook/0.5.1/ is now public with this fix.

**Pull request merged**
