### PR TITLE
move info to get_target so it doesn't show up with has_target

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Review by oscarlevin — CHANGES_REQUESTED** [review]
Good idea.  Can you reformat, and then feel free to complete the merge.

**Comment by StevenClontz** [comment]
will do (proposed the change without a codespace so didn't get formatting automatically)

**Comment by StevenClontz** [comment]
I wonder if there's a bot that could propose formatting fixes on PRs that otherwise pass tests...

**Comment by StevenClontz** [comment]
(Something is up with the codespace that is provisioned - I'm getting type errors from Pylance that don't seem to be errors on PRs, e.g.:

image

**Pull request merged**
